import { StyleSheet } from 'react-native';

export const roomCreationPreviewStyles = StyleSheet.create({
  actionPill: {
    alignItems: 'center',
    backgroundColor: '#202020',
    borderRadius: 38,
    flex: 1,
    flexDirection: 'row',
    height: 76,
    overflow: 'hidden',
    paddingRight: 16,
    position: 'relative',
  },
  actionPillLight: {
    backgroundColor: '#F4F5F6',
    borderColor: 'rgba(17,19,21,0.14)',
    borderWidth: 1,
    elevation: 8,
    shadowColor: '#111315',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
  },
  activeSessionField: { paddingLeft: 10, paddingRight: 14 },
  activeSessionInput: {
    backgroundColor: 'transparent',
    color: '#8B8B8B',
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    height: '100%',
    outlineColor: 'transparent',
    outlineWidth: 0,
    padding: 0,
  },
  controls: {
    alignItems: 'center',
    elevation: 20,
    flexDirection: 'row',
    gap: 12,
    position: 'absolute',
    zIndex: 20,
  },
  copy: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 36,
  },
  copyCenter: { alignSelf: 'center' },
  copyModeButton: { justifyContent: 'center', minHeight: 44 },
  copyRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  copyRight: { textAlign: 'right' },
  copyStack: {},
  copyWrap: {
    alignItems: 'center',
    backgroundColor: '#101111',
    flex: 1,
    justifyContent: 'center',
    marginTop: -2,
  },
  drawerUnderlay: {
    backgroundColor: '#F4F7FB',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 1,
  },
  image: { height: '100%', width: '100%' },
  imageCutoutShape: {
    bottom: -1,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  imageSeamCover: {
    backgroundColor: '#101111',
    bottom: -3,
    height: 6,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  imageWrap: {
    backgroundColor: '#101111',
    overflow: 'hidden',
    position: 'relative',
  },
  hidden: { opacity: 0 },
  menuFlyout: {
    alignItems: 'center',
    bottom: 88,
    gap: 10,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  menuFlyoutButton: {
    alignItems: 'center',
    backgroundColor: '#272727',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  menuFlyoutButtonLight: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(17,19,21,0.14)',
    borderWidth: 1,
    elevation: 6,
    shadowColor: '#111315',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  menuSlot: { position: 'relative' },
  nextControl: {
    alignItems: 'center',
    height: 76,
    justifyContent: 'center',
    marginLeft: 'auto',
    width: 48,
  },
  participate: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    height: 76,
    paddingLeft: 8,
    zIndex: 1,
  },
  participateOpen: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
  },
  participateText: {
    color: '#8B8B8B',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  participateTextLight: { color: '#24272A' },
  primaryControl: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 38,
    height: 76,
    justifyContent: 'center',
    position: 'relative',
    width: 76,
    zIndex: 3,
  },
  primaryControlLight: {
    borderColor: 'rgba(17,19,21,0.16)',
    borderWidth: 1,
    elevation: 10,
    shadowColor: '#111315',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
  },
  primaryControlHitArea: {
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  swipeTrace: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    height: 76,
    left: 0,
    position: 'absolute',
    top: 0,
    zIndex: 0,
  },
  swipeTraceLight: { backgroundColor: 'rgba(17,19,21,0.12)' },
  screen: { backgroundColor: '#101111', flex: 1, overflow: 'hidden', width: '100%' },
  secondaryControl: {
    alignItems: 'center',
    backgroundColor: '#272727',
    borderRadius: 38,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  secondaryControlLight: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(17,19,21,0.14)',
    borderWidth: 1,
    elevation: 8,
    shadowColor: '#111315',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
  },
  stage: {
    alignItems: 'stretch',
    backgroundColor: '#0B0B0C',
    flex: 1,
  },
});
