import { StyleSheet } from 'react-native';

import { colors, radii, spacing } from '@/theme';

export const examDetailStyles = StyleSheet.create({
  screen: { backgroundColor: colors.white, flex: 1, paddingHorizontal: spacing.xl },
  body: { paddingBottom: spacing.xxxl, paddingTop: spacing.lg },
  headerActions: { flexDirection: 'row', gap: spacing.sm },
  closedPill: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  closedText: { fontSize: 12, fontWeight: '700' },
  card: { backgroundColor: colors.surfaceDim, borderRadius: radii.lg, overflow: 'hidden' },
  cardBody: { padding: spacing.lg },
  accessCard: { marginTop: spacing.lg },
  loading: { paddingTop: spacing.xl },
  hero: {
    borderBottomLeftRadius: radii.md + 4,
    borderBottomRightRadius: radii.md + 4,
    height: 200,
    overflow: 'hidden',
  },
  ratingBadge: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radii.pill,
    height: 58,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.lg,
    top: 171,
    width: 58,
  },
  ratingBadgeText: { color: colors.ink, fontSize: 17, fontWeight: '800' },
  hotel: { color: colors.ink, fontSize: 22, fontWeight: '800' },
  ratingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  stars: { alignItems: 'center', flexDirection: 'row', gap: 3 },
  ratingText: { color: colors.inkSoft, fontSize: 13, fontWeight: '600', marginLeft: 5 },
  datesRow: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.lg },
  dateBox: {
    backgroundColor: colors.white,
    borderRadius: radii.sm,
    flex: 1,
    gap: 3,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg - 2,
  },
  dateLabel: { color: colors.muted, fontSize: 12, fontWeight: '500' },
  dateValue: { color: colors.ink, fontSize: 18, fontWeight: '700' },
  divider: {
    backgroundColor: colors.hairline,
    height: 1,
    marginHorizontal: -spacing.lg,
    marginVertical: spacing.lg,
  },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: spacing.xs },
  metaItem: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  metaText: { color: colors.ink, fontSize: 13, fontWeight: '600' },
  section: { color: colors.ink, fontSize: 18, fontWeight: '800', marginTop: spacing.xl },
  amenities: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg },
  amenity: { alignItems: 'center', gap: spacing.sm },
  amenityCircle: {
    alignItems: 'center',
    backgroundColor: colors.surfaceDim,
    borderRadius: radii.pill,
    height: 62,
    justifyContent: 'center',
    width: 62,
  },
  amenityLabel: { color: colors.inkSoft, fontSize: 11, fontWeight: '600' },
  priceRow: { alignItems: 'baseline', flexDirection: 'row', justifyContent: 'space-between' },
  price: { color: colors.ink, fontSize: 18, fontWeight: '800' },
  taxLabel: { color: colors.muted, fontSize: 14, fontWeight: '500', marginTop: spacing.md },
  tax: { color: colors.ink, fontSize: 15, fontWeight: '700' },
});
