import { StyleSheet } from 'react-native';

import { radii, spacing, type Palette } from '@/theme';

export const makeGroupSessionStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { backgroundColor: p.bg, flex: 1, paddingHorizontal: spacing.xl },
    body: { gap: spacing.lg, paddingBottom: spacing.xxxl, paddingTop: spacing.xl },
    rosterHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
    rosterSection: { gap: spacing.lg },
    rosterTitle: { color: p.ink, fontSize: 16, fontWeight: '700' },
    counter: {
      backgroundColor: p.primary12,
      borderRadius: radii.pill,
      minWidth: 26,
      paddingHorizontal: 7,
      paddingVertical: 2,
    },
    counterText: { color: p.primary, fontSize: 12, fontWeight: '700', textAlign: 'center' },
    roster: { alignItems: 'flex-start', gap: spacing.lg, paddingBottom: spacing.lg },
    student: { alignItems: 'center', gap: spacing.sm, width: 84 },
    studentName: { color: p.inkSoft, fontSize: 12, fontWeight: '600', textAlign: 'center' },
    sectionDivider: { backgroundColor: p.hairline, height: StyleSheet.hairlineWidth },
    methods: { flexDirection: 'row', justifyContent: 'space-evenly' },
    method: { alignItems: 'center', gap: spacing.sm },
    methodDisabled: { opacity: 0.4 },
    methodCircle: {
      alignItems: 'center',
      backgroundColor: p.surfaceDim,
      borderRadius: radii.pill,
      height: 62,
      justifyContent: 'center',
      width: 62,
    },
    methodLabel: { color: p.inkSoft, fontSize: 11, fontWeight: '600' },
    joinPrompt: { gap: spacing.lg, paddingVertical: spacing.xxl },
    rowCard: {
      alignItems: 'center',
      backgroundColor: p.surfaceDim,
      borderRadius: radii.lg,
      flexDirection: 'row',
      gap: spacing.lg,
      padding: spacing.lg,
    },
    thumb: { borderRadius: radii.sm, height: 64, overflow: 'hidden', width: 64 },
    tallThumb: { borderRadius: radii.sm, height: 96, overflow: 'hidden', width: 96 },
    rowText: { flex: 1, gap: 4 },
    rowTitle: { color: p.ink, fontSize: 16, fontWeight: '700' },
    rowSub: { color: p.muted, fontSize: 12, fontWeight: '500' },
    explore: { alignItems: 'center', flexDirection: 'row', gap: 3, marginTop: 2 },
    exploreText: { color: p.primary, fontSize: 12, fontWeight: '700' },
    drawerHint: { color: p.muted, fontSize: 13, fontWeight: '500' },
    input: {
      backgroundColor: p.surfaceDim,
      borderColor: p.hairline,
      borderRadius: radii.md,
      borderWidth: 1,
      color: p.ink,
      fontSize: 16,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
    },
    inputError: { borderColor: p.error },
    errorText: { color: p.error, fontSize: 12, fontWeight: '600' },
    joinButton: {
      alignItems: 'center',
      backgroundColor: p.primary,
      borderRadius: radii.pill,
      paddingVertical: spacing.lg - 2,
    },
    joinButtonText: { color: p.onPrimary, fontSize: 15, fontWeight: '700' },
  });
