import { StyleSheet } from 'react-native';

import { LIMEADE } from '@/screens/authConfig';

export const authScreenStyles = StyleSheet.create({
  layout: { flex: 1, justifyContent: 'flex-end' },
  bottomGroup: { alignSelf: 'center', gap: 14, maxWidth: 318, width: '100%' },
  verifyTitle: {
    color: '#FFFFFF',
    fontSize: 42,
    fontWeight: '100',
    lineHeight: 48,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.22)',
    textShadowOffset: { height: 1, width: 0 },
    textShadowRadius: 5,
  },
  accountTitle: { fontSize: 34, fontWeight: '600', lineHeight: 40 },
  // zIndex keeps the fields above the hero logo overlay so nothing sits over them.
  inputShell: {
    borderRadius: 29,
    height: 56,
    justifyContent: 'center',
    overflow: 'hidden',
    width: '100%',
    zIndex: 2,
  },
  passwordInput: { paddingRight: 54 },
  eyeToggle: {
    alignItems: 'center',
    height: 56,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: 0,
    width: 44,
    zIndex: 3,
  },
  inputIcon: { height: 56, justifyContent: 'center', left: 20, position: 'absolute', zIndex: 1 },
  input: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 29,
    borderWidth: 1,
    color: '#1B1B1D',
    fontSize: 16,
    height: 56,
    outlineColor: 'transparent',
    outlineWidth: 0,
    paddingLeft: 54,
    paddingRight: 24,
  },
  inputFocused: { borderColor: LIMEADE },
  // Wrapper carries the glow; the glass child carries overflow:hidden (the two can't
  // live on one node — a clipped view drops its shadow).
  primaryButtonWrap: {
    borderRadius: 29,
    elevation: 4,
    flex: 1,
    maxWidth: 190,
    shadowColor: LIMEADE,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 29,
    height: 52,
    justifyContent: 'center',
    overflow: 'hidden',
    width: '100%',
  },
  primaryButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  pressed: { transform: [{ scale: 0.97 }] },
  actionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    width: '100%',
  },
  socialWrap: {
    borderRadius: 26,
    elevation: 2,
    shadowColor: '#111111',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  socialButton: {
    alignItems: 'center',
    borderRadius: 26,
    height: 52,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 52,
  },
});
