import { StyleSheet } from 'react-native';

import { LIMEADE } from '@/screens/authConfig';

export const authScreenStyles = StyleSheet.create({
  layout: { flex: 1, justifyContent: 'space-between' },
  bottomGroup: { alignSelf: 'center', gap: 14, maxWidth: 318, width: '100%' },
  titleGroup: { alignItems: 'center' },
  verifyTitle: {
    color: '#FFFFFF',
    fontSize: 42,
    fontWeight: '100',
    lineHeight: 48,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.22)',
    textShadowOffset: { height: 1, width: 0 },
    textShadowRadius: 5,
  },
  accountTitle: { fontSize: 34, fontWeight: '600', lineHeight: 40 },
  errorPill: {
    backgroundColor: 'rgba(217, 83, 79, 0.92)',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  errorText: { color: '#FFFFFF', fontSize: 13, fontWeight: '600', textAlign: 'center' },
  inputShell: { width: '100%' },
  inputIcon: { height: 50, justifyContent: 'center', left: 20, position: 'absolute', zIndex: 1 },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#F3F4F6',
    borderRadius: 29,
    borderWidth: 1,
    color: '#1B1B1D',
    elevation: 2,
    fontSize: 16,
    height: 50,
    outlineColor: 'transparent',
    outlineWidth: 0,
    paddingLeft: 54,
    paddingRight: 24,
    shadowColor: '#111111',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  inputFocused: { borderColor: LIMEADE },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: LIMEADE,
    borderRadius: 29,
    elevation: 4,
    flex: 1,
    height: 52,
    justifyContent: 'center',
    maxWidth: 190,
    shadowColor: LIMEADE,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
  },
  primaryButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  pressed: { opacity: 0.84, transform: [{ scale: 0.98 }] },
  disabled: { opacity: 0.6 },
  actionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    width: '100%',
  },
  socialButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#F3F4F6',
    borderRadius: 26,
    borderWidth: 1,
    elevation: 2,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  darkSocialButton: { backgroundColor: '#000000', borderColor: '#000000' },
});
