import { StyleSheet } from 'react-native';

export const nfcVerificationStyles = StyleSheet.create({
  screen: { backgroundColor: '#F2F3FF', flex: 1, overflow: 'hidden' },
  nav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 16,
    position: 'absolute',
    right: 16,
    zIndex: 2,
  },
  navButton: {
    alignItems: 'center',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  navSpacer: { width: 40 },
  brandTitle: {
    color: '#3A6700',
    fontSize: 42,
    fontWeight: '100',
    lineHeight: 48,
    textAlign: 'center',
  },
  scroll: { flex: 1, width: '100%' },
  content: {
    alignItems: 'center',
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  header: { alignItems: 'center' },
  roomCodeCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: 'rgba(92,158,8,0.18)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  roomCodeLabel: {
    color: '#8A9382',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  roomCodeText: {
    color: '#3A6700',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 2,
  },
  scanArea: {
    alignItems: 'center',
    aspectRatio: 1,
    justifyContent: 'center',
    maxWidth: 360,
    width: '100%',
  },
  rippleLayer: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  ripple: {
    backgroundColor: 'rgba(58, 103, 0, 0.22)',
    borderRadius: 64,
    height: 128,
    position: 'absolute',
    width: 128,
  },
  scanContent: {
    alignItems: 'center',
    gap: 28,
    justifyContent: 'center',
    zIndex: 1,
  },
  scanIconStage: {
    alignItems: 'center',
    height: 280,
    justifyContent: 'center',
    width: 280,
  },
  scanIconShell: {
    alignItems: 'center',
    backgroundColor: '#C1F27E',
    borderRadius: 64,
    elevation: 8,
    height: 128,
    justifyContent: 'center',
    shadowColor: '#3A6700',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    width: 128,
  },
  scanCopy: { alignItems: 'center' },
  scanTitle: {
    color: '#3A6700',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0.4,
    lineHeight: 32,
    textAlign: 'center',
  },
  footer: {
    gap: 14,
    maxWidth: 320,
    width: '100%',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  manualButton: {
    alignItems: 'center',
    borderColor: '#727A66',
    borderRadius: 28,
    borderWidth: 2,
    flex: 1,
    height: 56,
    justifyContent: 'center',
  },
  manualButtonPressed: { backgroundColor: '#DAE2FD' },
  manualText: {
    color: '#131B2E',
    fontSize: 12,
    fontWeight: '700',
  },
  faceButton: {
    alignItems: 'center',
    backgroundColor: '#EAF8F0',
    borderColor: 'rgba(92,158,8,0.16)',
    borderRadius: 28,
    borderWidth: 1,
    flex: 1,
    height: 56,
    justifyContent: 'center',
  },
  faceText: { color: '#3A6700', fontSize: 12, fontWeight: '800' },
  drawerOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 6,
  },
  drawerScrim: {
    backgroundColor: 'rgba(8, 18, 12, 0.38)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  manualDrawer: {
    backgroundColor: 'rgba(244, 247, 251, 0.96)',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    bottom: 0,
    gap: 14,
    left: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    position: 'absolute',
    right: 0,
  },
  drawerHandle: {
    alignSelf: 'center',
    backgroundColor: '#C7D0DA',
    borderRadius: 2,
    height: 4,
    marginBottom: 8,
    width: 42,
  },
  drawerInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EDF1F5',
    borderRadius: 25,
    borderWidth: 1,
    color: '#10231D',
    fontSize: 16,
    height: 50,
    outlineColor: 'transparent',
    outlineWidth: 0,
    paddingHorizontal: 16,
  },
  drawerSubmit: {
    alignItems: 'center',
    backgroundColor: '#5C9E08',
    borderRadius: 25,
    height: 50,
    justifyContent: 'center',
  },
  drawerSubmitText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  cameraScreen: { backgroundColor: '#050807', flex: 1 },
  cameraPreview: {
    backgroundColor: '#0B1010',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  cameraTopBar: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 14,
    position: 'absolute',
    right: 14,
    zIndex: 2,
  },
  cameraCloseButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  cameraCopy: { alignItems: 'center', gap: 2 },
  cameraTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '700', textAlign: 'center' },
  cameraText: { color: 'rgba(255,255,255,0.72)', fontSize: 13, textAlign: 'center' },
  cameraSpacer: { width: 40 },
  cameraBottomBar: {
    alignItems: 'center',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 2,
  },
  cameraSendButton: {
    alignItems: 'center',
    backgroundColor: '#5C9E08',
    borderRadius: 35,
    height: 70,
    justifyContent: 'center',
    width: 70,
  },
});
