import { StyleSheet } from 'react-native';

import { LIMEADE } from '@/screens/authConfig';

export const roomSetupStyles = StyleSheet.create({
  screen: { backgroundColor: '#EEF9EC', flex: 1, overflow: 'hidden' },
  circleButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(244,247,251,0.88)',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  hidden: { opacity: 0 },
  formScroll: { flex: 1, width: '100%' },
  formScrollContent: { alignItems: 'center' },
  expandedForm: {
    alignSelf: 'center',
    flex: 1,
    gap: 9,
    maxWidth: 360,
    width: '100%',
  },
  row: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  formDivider: { backgroundColor: '#E2E8EE', height: 1, marginVertical: 2, width: '100%' },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EDF1F5',
    borderRadius: 25,
    borderWidth: 1,
    color: '#10231D',
    flex: 1,
    fontSize: 16,
    height: 50,
    outlineColor: 'transparent',
    outlineWidth: 0,
    paddingHorizontal: 16,
  },
  rangeInput: { flexBasis: 0, minWidth: 0 },
  floor: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EDF1F5',
    borderRadius: 25,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    height: 50,
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  floorButton: {
    alignItems: 'center',
    backgroundColor: '#F3F6F8',
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  floorText: { color: '#10231D', flex: 1, fontSize: 16, fontWeight: '700', textAlign: 'center' },
  roundAction: {
    alignItems: 'center',
    backgroundColor: LIMEADE,
    borderRadius: 25,
    elevation: 4,
    height: 50,
    justifyContent: 'center',
    shadowColor: LIMEADE,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    width: 50,
  },
  mutedAction: { backgroundColor: '#EEF2F5', elevation: 0, shadowOpacity: 0 },
  actions: { gap: 8, width: '100%' },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, width: '100%' },
  chip: {
    backgroundColor: 'rgba(92,158,8,0.08)',
    borderColor: 'rgba(92,158,8,0.18)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    height: 38,
    justifyContent: 'center',
    minWidth: 102,
    paddingHorizontal: 8,
    paddingRight: 20,
    position: 'relative',
  },
  chipText: {
    color: '#0C2A1C',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
  },
  chipEditButton: {
    alignItems: 'center',
    height: 16,
    justifyContent: 'center',
    position: 'absolute',
    right: 4,
    top: 4,
    width: 16,
  },
});
