import { StyleSheet } from 'react-native';

import { LIMEADE } from '@/screens/authConfig';

export const roomSetupStyles = StyleSheet.create({
  screen: { backgroundColor: '#EEF9EC', flex: 1, overflow: 'hidden' },
  hero: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  topNav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 12,
    position: 'absolute',
    right: 12,
    zIndex: 8,
  },
  navTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '100',
    letterSpacing: 2.5,
    textTransform: 'uppercase',
  },
  circleButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(244,247,251,0.88)',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  hidden: { opacity: 0 },
  navSpacer: { width: 36 },
  homeNavLeft: { alignItems: 'center', flexDirection: 'row', width: 44 },
  homeNavButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(244,247,251,0.2)',
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 18,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  homeSearchShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(244,247,251,0.2)',
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    height: 36,
    marginHorizontal: 8,
    overflow: 'hidden',
    paddingLeft: 12,
    paddingRight: 6,
  },
  homeSearchInput: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    color: '#FFFFFF',
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    outlineColor: 'transparent',
    outlineWidth: 0,
    padding: 0,
  },
  homeSearchClose: {
    alignItems: 'center',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  searchSubmitButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(244,247,251,0.2)',
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    height: 36,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  searchSubmitContent: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
  },
  searchSubmitSlot: { alignItems: 'flex-end', width: 76 },
  searchSubmitText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
  quickActionMenu: {
    backgroundColor: 'rgba(244,247,251,0.96)',
    borderColor: 'rgba(92,158,8,0.16)',
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
    left: 0,
    padding: 8,
    position: 'absolute',
    top: 44,
    width: 164,
    zIndex: 20,
  },
  quickActionRow: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 34 },
  quickActionText: { color: 'rgba(19,27,46,0.68)', fontSize: 13, fontWeight: '500' },
  logoAnchor: { alignItems: 'center', left: 0, position: 'absolute', right: 0, zIndex: 1 },
  sheet: {
    alignItems: 'center',
    backgroundColor: '#F4F7FB',
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    bottom: 0,
    justifyContent: 'flex-start',
    left: 0,
    paddingHorizontal: 20,
    paddingTop: 0,
    position: 'absolute',
    right: 0,
  },
  expandedSheet: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    height: '85%',
    paddingTop: 58,
  },
  expandedLogo: { alignItems: 'center', marginBottom: 34 },
  collapsedSessionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    position: 'absolute',
    zIndex: 2,
  },
  orDivider: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    left: 20,
    position: 'absolute',
    right: 20,
    zIndex: 2,
  },
  orLine: { backgroundColor: 'rgba(244,247,251,0.72)', flex: 1, height: 1 },
  orText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  arrowStack: { alignItems: 'center' },
  stackedArrow: { marginTop: -13 },
  swipePromptOverlay: {
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 2,
  },
  swipePrompt: {
    alignItems: 'center',
    gap: 16,
    justifyContent: 'center',
    paddingBottom: 18,
    paddingTop: 18,
    width: '100%',
  },
  swipeText: { color: '#6F879E', fontSize: 13, fontWeight: '700' },
  formScroll: { flex: 1, width: '100%' },
  formScrollContent: { alignItems: 'center' },
  expandedForm: {
    alignSelf: 'center',
    flex: 1,
    gap: 9,
    maxWidth: 360,
    width: '100%',
  },
  row: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  formDivider: { backgroundColor: '#E2E8EE', height: 1, marginVertical: 2, width: '100%' },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EDF1F5',
    borderRadius: 25,
    borderWidth: 1,
    color: '#10231D',
    flex: 1,
    fontSize: 16,
    height: 50,
    outlineColor: 'transparent',
    outlineWidth: 0,
    paddingHorizontal: 16,
  },
  rangeInput: { flexBasis: 0, minWidth: 0 },
  floor: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EDF1F5',
    borderRadius: 25,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    height: 50,
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  floorButton: {
    alignItems: 'center',
    backgroundColor: '#F3F6F8',
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  floorText: { color: '#10231D', flex: 1, fontSize: 16, fontWeight: '700', textAlign: 'center' },
  roundAction: {
    alignItems: 'center',
    backgroundColor: LIMEADE,
    borderRadius: 25,
    elevation: 4,
    height: 50,
    justifyContent: 'center',
    shadowColor: LIMEADE,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    width: 50,
  },
  mutedAction: { backgroundColor: '#EEF2F5', elevation: 0, shadowOpacity: 0 },
  skipText: {
    alignSelf: 'center',
    color: LIMEADE,
    fontSize: 12,
    fontWeight: '700',
    paddingVertical: 2,
  },
  actions: { gap: 8, width: '100%' },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, width: '100%' },
  chip: {
    backgroundColor: 'rgba(92,158,8,0.08)',
    borderColor: 'rgba(92,158,8,0.18)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    height: 38,
    justifyContent: 'center',
    minWidth: 102,
    paddingHorizontal: 8,
    paddingRight: 20,
    position: 'relative',
  },
  chipText: {
    color: '#0C2A1C',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
  },
  chipEditButton: {
    alignItems: 'center',
    height: 16,
    justifyContent: 'center',
    position: 'absolute',
    right: 4,
    top: 4,
    width: 16,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#EAF8F0',
    borderColor: 'rgba(92,158,8,0.16)',
    borderRadius: 25,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    height: 50,
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 9,
  },
  saveText: { color: LIMEADE, fontSize: 15, fontWeight: '800' },
  saveIcon: {
    alignItems: 'center',
    backgroundColor: LIMEADE,
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
});
