import { StyleSheet } from 'react-native';

import { radii, shadows, spacing, type Palette } from '@/theme';

export const makeSessionWizardStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { backgroundColor: p.bg, flex: 1, paddingHorizontal: spacing.xl },
    topBar: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: spacing.md,
      paddingVertical: spacing.sm,
    },
    topClose: {
      alignItems: 'center',
      backgroundColor: p.surfaceDim,
      borderRadius: radii.pill,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    topTitle: { color: p.ink, flex: 1, fontSize: 16, fontWeight: '700' },
    topSpacer: { height: 40, width: 40 },
    progress: { flexDirection: 'row', gap: spacing.sm, paddingVertical: spacing.md },
    dot: { backgroundColor: p.hairline, borderRadius: radii.pill, flex: 1, height: 4 },
    dotActive: { backgroundColor: p.primary },
    body: { gap: spacing.lg, paddingBottom: spacing.xxxl, paddingTop: spacing.md },
    section: { gap: spacing.md },
    hint: { color: p.muted, fontSize: 13, fontWeight: '500' },
    row: { flexDirection: 'row', gap: spacing.md },
    flex: { flex: 1 },
    field: { gap: spacing.xs },
    fieldLabel: { color: p.inkSoft, fontSize: 13, fontWeight: '700' },
    input: {
      backgroundColor: p.surfaceDim,
      borderColor: p.hairline,
      borderRadius: radii.md,
      borderWidth: 1,
      color: p.ink,
      fontSize: 16,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
    },
    courseCard: {
      backgroundColor: p.surfaceDim,
      borderRadius: radii.lg,
      gap: spacing.sm,
      padding: spacing.md,
    },
    courseRemove: {
      alignItems: 'center',
      backgroundColor: p.bg,
      borderRadius: radii.pill,
      height: 28,
      justifyContent: 'center',
      position: 'absolute',
      right: spacing.sm,
      top: spacing.sm,
      width: 28,
      zIndex: 1,
    },
    addRange: { paddingVertical: spacing.sm },
    addRangeText: { color: p.primary, fontSize: 14, fontWeight: '700' },
    methodGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
    methodChip: {
      borderRadius: radii.pill,
      borderWidth: 1.5,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.sm + 2,
    },
    methodChipText: { fontSize: 14, fontWeight: '700' },
    reviewRow: {
      borderBottomColor: p.hairline,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: spacing.md,
    },
    reviewLabel: { color: p.muted, fontSize: 13, fontWeight: '600' },
    reviewValue: { color: p.ink, flex: 1, fontSize: 14, fontWeight: '700', textAlign: 'right' },
    footer: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: spacing.md,
      marginBottom: spacing.xxl,
    },
    backFab: {
      alignItems: 'center',
      backgroundColor: p.surfaceDim,
      borderColor: p.hairline,
      borderRadius: 30,
      borderWidth: 1,
      height: 60,
      justifyContent: 'center',
      width: 60,
    },
    cta: {
      alignItems: 'center',
      backgroundColor: p.primary,
      borderRadius: radii.pill,
      flex: 1,
      paddingVertical: spacing.lg - 2,
    },
    ctaDisabled: { opacity: 0.4 },
    ctaText: { color: p.onPrimary, fontSize: 15, fontWeight: '700' },
    nextFab: {
      alignItems: 'center',
      backgroundColor: p.primary,
      borderRadius: 30,
      height: 60,
      justifyContent: 'center',
      marginLeft: 'auto',
      width: 60,
      ...shadows.floating,
    },
  });
