import { colors } from '@/theme';
import { StyleSheet } from 'react-native';

export const studentVerificationResultStyles = StyleSheet.create({
  screen: { backgroundColor: '#F2F3FF', flex: 1 },
  nav: {
    left: 16,
    position: 'absolute',
    right: 16,
    zIndex: 2,
  },
  navButton: {
    alignItems: 'center',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  scroll: { flex: 1, width: '100%' },
  content: {
    alignItems: 'center',
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 24,
  },
  statusGroup: { alignItems: 'center', gap: 6 },
  statusLabel: {
    color: '#3A6700',
    fontSize: 42,
    fontWeight: '100',
    lineHeight: 48,
    textAlign: 'center',
  },
  statusText: { color: '#65705E', fontSize: 15, lineHeight: 21, textAlign: 'center' },
  photoWrap: {
    alignItems: 'center',
    height: 188,
    justifyContent: 'center',
    width: 188,
  },
  photo: {
    borderColor: '#FFFFFF',
    borderRadius: 82,
    borderWidth: 5,
    height: 164,
    width: 164,
  },
  badge: {
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    bottom: 10,
    padding: 3,
    position: 'absolute',
    right: 12,
  },
  studentBlock: { alignItems: 'center', gap: 5, width: '100%' },
  studentName: {
    color: '#131B2E',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 32,
    textAlign: 'center',
  },
  studentMeta: { color: '#414938', fontSize: 15, lineHeight: 21, textAlign: 'center' },
  classState: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  actions: { gap: 14, maxWidth: 320, width: '100%' },
  classButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
  },
  removeButton: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(186, 26, 26, 0.24)',
    borderWidth: 1,
  },
  classButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  removeButtonText: { color: '#BA1A1A' },
  closeTextButton: { alignItems: 'center', paddingVertical: 4 },
  closeText: {
    color: '#414938',
    fontSize: 14,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
});
